### ISSUE TITLE
project which use this module

### ISSUE THREAD

**Issue by Scorfly** [mila-labs/swig-i18n-abide#1]
Hi,

Do you know an open source project which use this module ?
I'm trying to use it, but it doesn't work.

Best regards,
Louis

**Comment by mweibel** [comment]
No, we use it in our project though. 

Can you please explain what doesn't work?

**Comment by Scorfly** [comment]
thx for the reply, if you have a little time to check : 

mod installed 

```
$ ls node_modules/
body-parser    debug    i18n-abide  mysql  static-favicon  swig-i18n-abide
cookie-parser  express  morgan      orm    swig
```

my app.js

``` javascript
//[..]
var express = require('express');
var path = require('path');
var swig = require('swig');
var i18n = require('i18n-abide')
require('swig-i18n-abide')(swig);
//[..]
var app = express();
app.use(
    i18n.abide({
        supported_languages: ['en', 'fr'],
        default_lang: 'en',
        debug_lang: 'en',
        translation_directory: __dirname + '/locales'
    })
);
//[..]
```

my locales :

locales/fr/messages.json

```
{
    "hello": "Salut"
}
```

in my view I've :

```
    {% trans "connect" %}
```

The browser print the key in reverse :

```
oʅʅǝɥ
```

Do you have an idea ?

**Comment by mweibel** [comment]
This is actually a proof that it does indeed work: 
https://github.com/mozilla/i18n-abide#debugging-and-testing

You have set the debug lang to en, therefore it will set the lang to en + reverse it. 
On the other hand I don't know why you call trans with "connect" and in your messages file you don't have connect..

**Comment by mweibel** [comment]
Everything all right? 

Btw. I just released a fix to prevent XSS.. if you use this module you might want to update :)

**Comment by Scorfly** [comment]
finally we choosed ejs + i18n 
and it works directly.

Thx for your feedback
