### ISSUE TITLE
Could you tell me how to set it?

### ISSUE THREAD

**Issue by iunknownexist** [mila-labs/swig-i18n-abide#2]
I have required "swig, i18n-abide, swig-i18n-abide", and used "{% trans 'String' %}" in the  html templates. But I don't know how to set the translation files, such as en_US. 
Could you tell me how to set it and where?  Thanks!

我在 app.js 中已经引入了swig、i18n-abide、swig-i18n-abide，在 html 模板中也用了trans标签。但是我不知道它从哪里读取翻译文件输出翻译后的内容。 你能告诉我怎么设置吗？ 谢谢。

**Comment by Pavel-vo** [comment]
This articles may help you
Mozilla Hacks blog has a three part introduction.
https://hacks.mozilla.org/2013/04/localize-your-node-js-service-part-1-of-3-a-node-js-holiday-season-part-9/
https://hacks.mozilla.org/2013/04/localization-community-tools-process-part-2-of-3-a-node-js-holiday-season-part-10/
https://hacks.mozilla.org/2013/04/localization-in-action-part-3-of-3-a-node-js-holiday-season-part-11/

**Comment by iunknownexist** [comment]
I'm sorrry reply you so late. 
Now I know how to resolve the problem.
Thank you very much.
